In [ ]:
!pip install seaborn

In [ ]:
# import python libraries

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt # visualizing data
%matplotlib inline
import seaborn as sns

In [21]:
# import csv file
df = pd.read_csv(r'D:\Python_Diwali_Sales_Analysis-main\Python_Diwali_Sales_Analysis-main\Diwali Sales Data.csv', encoding= 'unicode_escape')

In [35]:
df.shape

(11239, 13)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11239 entries, 0 to 11250
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11239 non-null  int64
 1   Cust_name         11239 non-null  object
 2   Product_ID        11239 non-null  object
 3   Gender            11239 non-null  object
 4   Age Group         11239 non-null  object
 5   Age               11239 non-null  int64
 6   Marital_Status    11239 non-null  int64
 7   State             11239 non-null  object
 8   Zone              11239 non-null  object
 9   Occupation        11239 non-null  object
 10  Product_Category  11239 non-null  object
 11  Orders            11239 non-null  int64
 12  Amount            11239 non-null  int64
dtypes: int64(5), object(8)
memory usage: 1.2+ MB

In [23]:
df.head(10)

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.00,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.00,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.00,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.00,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.00,NaN,NaN
5,1000588,Joni,P00057942,M,26-35,28,1,Himachal Pradesh,Northern,Food Processing,Auto,1,23877.00,NaN,NaN
6,1001132,Balk,P00018042,F,18-25,25,1,Uttar Pradesh,Central,Lawyer,Auto,4,23841.00,NaN,NaN
7,1002092,Shivangi,P00273442,F,55+,61,0,Maharashtra,Western,IT Sector,Auto,1,NaN,NaN,NaN
8,1003224,Kushal,P00205642,M,26-35,35,0,Uttar Pradesh,Central,Govt,Auto,2,23809.00,NaN,NaN
9,1003650,Ginny,P00031142,F,26-35,26,1,Andhra Pradesh,Southern,Media,Auto,4,23799.99,NaN,NaN

In [25]:
#drop unrelated/blank columns
df.drop(['Status', 'unnamed1'], axis=1, inplace=True)

In [31]:
#check for null values
pd.isnull(df).sum()

User_ID             0
Cust_name           0
Product_ID          0
Gender              0
Age Group           0
Age                 0
Marital_Status      0
State               0
Zone                0
Occupation          0
Product_Category    0
Orders              0
Amount              0
dtype: int64

In [34]:
# drop null values
df.dropna(inplace=True)

In [36]:
# change data type
df['Amount'] = df['Amount'].astype('int')

In [37]:
df['Amount'].dtypes

dtype('int64')

In [38]:
df.columns

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital_Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders', 'Amount'],
      dtype='object')

In [41]:
#rename column
df.rename(columns= {'Marital_Status':'Shaadi'})

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Shaadi,State,Zone,Occupation,Product_Category,Orders,Amount
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11246,1000695,Manning,P00296942,M,18-25,19,1,Maharashtra,Western,Chemical,Office,4,370
11247,1004089,Reichenbach,P00171342,M,26-35,33,0,Haryana,Northern,Healthcare,Veterinary,3,367
11248,1001209,Oshin,P00201342,F,36-45,40,0,Madhya Pradesh,Central,Textile,Office,4,213
11249,1004023,Noonan,P00059442,M,36-45,37,0,Karnataka,Southern,Agriculture,Office,3,206
11250,1002744,Brumley,P00281742,F,18-25,19,0,Maharashtra,Western,Healthcare,Office,3,188

In [42]:
# describe() method returns description of the data in the DataFrame (i.e. count, mean, std, etc)
df.describe()

            User_ID           Age  Marital_Status        Orders        Amount
count  1.123900e+04  11239.000000    11239.000000  11239.000000  11239.000000
mean   1.003004e+06     35.410357        0.420055      2.489634   9453.610553
std    1.716039e+03     12.753866        0.493589      1.114967   5222.355168
min    1.000001e+06     12.000000        0.000000      1.000000    188.000000
25%    1.001492e+06     27.000000        0.000000      2.000000   5443.000000
50%    1.003064e+06     33.000000        0.000000      2.000000   8109.000000
75%    1.004426e+06     43.000000        1.000000      3.000000  12675.000000
max    1.006040e+06     92.000000        1.000000      4.000000  23952.000000

In [14]:
# use describe() for specific columns
df[['Age', 'Orders', 'Amount']].describe()

                Age        Orders        Amount
count  11239.000000  11239.000000  11239.000000
mean      35.410357      2.489634   9453.610553
std       12.753866      1.114967   5222.355168
min       12.000000      1.000000    188.000000
25%       27.000000      2.000000   5443.000000
50%       33.000000      2.000000   8109.000000
75%       43.000000      3.000000  12675.000000
max       92.000000      4.000000  23952.000000

In [ ]:
1. Which gender contributes the highest sales?

In [43]:
df.groupby('Gender')['Amount'].sum().sort_values(ascending=False)

Gender
F    74335853
M    31913276
Name: Amount, dtype: int64

In [ ]:
insight: Female customers generated the highest sales revenue.

In [ ]:
2. Which age group spends the most?

In [44]:
df.groupby('Age Group')['Amount'].sum().sort_values(ascending=False)

Age Group
26-35    42613442
36-45    22144994
18-25    17240732
46-50     9207844
51-55     8261477
55+       4080987
0-17      2699653
Name: Amount, dtype: int64

In [ ]:
insight: Age Group 26-35 contributes the highest revenue.

In [ ]:
3. Which state generates the highest revenue?

In [45]:
df.groupby('State')['Amount'].sum().sort_values(ascending=False).head(10)

State
Uttar Pradesh       19374968
Maharashtra         14427543
Karnataka           13523540
Delhi               11603818
Madhya Pradesh       8101142
Andhra Pradesh       8037146
Himachal Pradesh     4963368
Haryana              4220175
Bihar                4022757
Gujarat              3946082
Name: Amount, dtype: int64

In [ ]:
Insight: Uttar Pradesh state generated the highest revenue.

In [ ]:
4. Which zone contributes the most revenue?

In [46]:
df.groupby('Zone')['Amount'].sum().sort_values(ascending=False)

Zone
Central     41600872
Southern    26606667
Western     18373625
Northern    12618752
Eastern      7049213
Name: Amount, dtype: int64

In [ ]:
Insight: Central zone contributes the highest sales.

In [ ]:
5. Which occupation generates the highest revenue?

In [47]:
df.groupby('Occupation')['Amount'].sum().sort_values(ascending=False)

Occupation
IT Sector          14755079
Healthcare         13034586
Aviation           12602298
Banking            10770610
Govt                8517212
Hospitality         6376405
Media               6295832
Automobile          5368596
Chemical            5297436
Lawyer              4981665
Retail              4783170
Food Processing     4070670
Construction        3597511
Textile             3204972
Agriculture         2593087
Name: Amount, dtype: int64

In [ ]:
Insight: IT Sector occupation contributes the highest revenue.

In [ ]:
6. Which product category generates the highest revenue?

In [48]:
df.groupby('Product_Category')['Amount'].sum().sort_values(ascending=False)

Product_Category
Food                     33933883
Clothing & Apparel       16495019
Electronics & Gadgets    15643846
Footwear & Shoes         15575209
Furniture                 5440051
Games & Toys              4331694
Sports Products           3635933
Beauty                    1959484
Auto                      1958609
Stationery                1676051
Household items           1569337
Tupperware                1155642
Books                     1061478
Decor                      730360
Pet Care                   482277
Hand & Power Tools         405618
Veterinary                 112702
Office                      81936
Name: Amount, dtype: int64

In [ ]:
Insight: Food product category generates the highest sales.

In [ ]:
7. Which product category receives the highest number of orders?

In [49]:
df.groupby('Product_Category')['Orders'].sum().sort_values(ascending=False)

Product_Category
Clothing & Apparel       6634
Food                     6110
Electronics & Gadgets    5226
Footwear & Shoes         2646
Household items          1331
Beauty                   1086
Games & Toys              940
Furniture                 889
Sports Products           870
Pet Care                  536
Stationery                281
Office                    261
Books                     245
Auto                      239
Decor                     235
Veterinary                206
Tupperware                166
Hand & Power Tools         80
Name: Orders, dtype: int64

In [ ]:
Insight: Clothing & Apparel category receives the highest orders.

In [ ]:
8. What is the average spending by gender?

In [50]:
df.groupby('Gender')['Amount'].mean().sort_values(ascending=False)

Gender
F    9491.298902
M    9366.972703
Name: Amount, dtype: float64

In [ ]:
Insight: Female customers spend more on average.

In [ ]:
9. Which marital status group spends more?

In [51]:
df.groupby('Marital_Status')['Amount'].sum()

Marital_Status
0    62125384
1    44123745
Name: Amount, dtype: int64

In [ ]:
Insight: Married/Unmarried customers spend more.

In [ ]:
10. Which state has the highest number of orders?

In [52]:
df.groupby('State')['Orders'].sum().sort_values(ascending=False)

State
Uttar Pradesh       4807
Maharashtra         3810
Karnataka           3240
Delhi               2740
Madhya Pradesh      2252
Andhra Pradesh      2051
Himachal Pradesh    1568
Kerala              1137
Haryana             1109
Gujarat             1066
Bihar               1062
Jharkhand            953
Uttarakhand          824
Rajasthan            555
Punjab               495
Telangana            312
Name: Orders, dtype: int64

In [ ]:
Insight: Uttar Pradesh state has the highest order count.

In [ ]:
11. Which occupation places the highest number of orders?

In [53]:
df.groupby('Occupation')['Orders'].sum().sort_values(ascending=False)

Occupation
IT Sector          3997
Healthcare         3455
Aviation           3215
Banking            2817
Govt               2155
Hospitality        1739
Media              1596
Automobile         1371
Lawyer             1344
Chemical           1309
Retail             1270
Food Processing    1073
Construction       1025
Textile             893
Agriculture         722
Name: Orders, dtype: int64

In [ ]:
Insight: IT Sector occupation places the most orders.

In [ ]:
12. Which age group places the highest number of orders?

In [54]:
df.groupby('Age Group')['Orders'].sum().sort_values(ascending=False)

Age Group
26-35    11395
36-45     5687
18-25     4650
46-50     2371
51-55     2112
55+       1076
0-17       690
Name: Orders, dtype: int64

In [ ]:
Insight: Age group 26-35 places the highest orders.

In [ ]:
13. Which state has the highest average order value?

In [55]:
df.groupby('State')['Amount'].mean().sort_values(ascending=False)

State
Delhi               10510.704710
Karnataka           10370.812883
Uttar Pradesh        9966.547325
Andhra Pradesh       9910.167694
Maharashtra          9460.683934
Haryana              9336.670354
Bihar                9269.025346
Gujarat              9241.409836
Telangana            9211.920000
Madhya Pradesh       8796.028230
Kerala               8597.110375
Rajasthan            8265.839827
Himachal Pradesh     8163.434211
Jharkhand            7964.357895
Uttarakhand          7877.950000
Punjab               7629.000000
Name: Amount, dtype: float64

In [ ]:
Insight: Delhi state has the highest average purchase value.

In [ ]:
14. Which gender places more orders?

In [56]:
df.groupby('Gender')['Orders'].sum().sort_values(ascending=False)

Gender
F    19548
M     8433
Name: Orders, dtype: int64

In [ ]:
Insight: Female customers place more orders.

In [ ]:
15. Which occupation-category combination generates the highest revenue?

In [57]:
df.groupby(['Occupation','Product_Category'])['Amount'].sum().sort_values(ascending=False).head(10)

Occupation  Product_Category
IT Sector   Food                     4655906
Healthcare  Food                     4465342
Aviation    Food                     4306343
Govt        Food                     3242839
Banking     Food                     2894943
Media       Food                     2351254
IT Sector   Footwear & Shoes         2284568
Healthcare  Clothing & Apparel       2249961
IT Sector   Clothing & Apparel       2226012
            Electronics & Gadgets    2220174
Name: Amount, dtype: int64

In [ ]:
Insight: IT Sector occupation purchasing XYZ category generates the highest revenue.

In [ ]:
16. Top 10 customers by spending

In [58]:
df.groupby('Cust_name')['Amount'].sum().sort_values(ascending=False).head(10)

Cust_name
Vishakha     382782
Sudevi       287142
Vasudev      281034
Neola        275234
Alejandro    272517
Aastha       266961
Shreyshi     265603
Hazel        242343
Akshat       241349
Gopal        239147
Name: Amount, dtype: int64

In [ ]:
Insight: Top customers contribute significantly to total revenue.

In [ ]:
17. Which age group buys the most products in each category?

In [59]:
pd.crosstab(df['Age Group'], df['Product_Category'])

Product_Category,Auto,Beauty,Books,Clothing & Apparel,Decor,Electronics & Gadgets,Food,Footwear & Shoes,Furniture,Games & Toys,Hand & Power Tools,Household items,Office,Pet Care,Sports Products,Stationery,Tupperware,Veterinary
Age Group,,,,,,,,,,,,,,,,,,
0-17,3,9,1,72,1,61,83,6,13,10,0,14,5,3,10,4,0,1
18-25,17,77,20,469,19,343,478,45,68,51,6,115,24,34,66,17,17,13
26-35,43,164,41,1057,33,832,991,424,136,163,10,271,41,87,134,53,19,42
36-45,18,82,22,532,23,413,454,305,69,84,7,75,23,37,82,24,19,14
46-50,4,33,9,234,10,186,213,120,29,35,0,23,7,32,27,6,9,6
51-55,8,37,7,188,5,177,168,108,26,28,1,14,7,13,27,6,7,3
55+,4,20,3,103,5,75,103,51,11,15,2,8,6,6,10,2,1,2

In [ ]:
Insight: Different age groups prefer different product categories.

In [ ]:
18. Revenue contribution by top 5 states

In [60]:
top5 = df.groupby('State')['Amount'].sum().sort_values(ascending=False).head(5)
(top5.sum()/df['Amount'].sum())*100

np.float64(63.088527530423335)

In [ ]:
Insight: Top 5 states contribute 63.088527530423335% of total revenue.

In [ ]:
19. Which zone has the highest average spending?

In [61]:
df.groupby('Zone')['Amount'].mean().sort_values(ascending=False)

Zone
Southern    9879.935759
Central     9699.433901
Western     9412.717725
Eastern     8659.966830
Northern    8463.281019
Name: Amount, dtype: float64

In [ ]:
Insight: XYZ zone has the highest average spending.

In [ ]:
20. Most valuable customer segment (Gender + Marital Status)

In [62]:
df.groupby(['Gender','Marital_Status'])['Amount'].sum().sort_values(ascending=False)

Gender  Marital_Status
F       0                 43786646
        1                 30549207
M       0                 18338738
        1                 13574538
Name: Amount, dtype: int64

In [ ]:
Insight: Female customer segment is the most valuable.